---
title: "r-tables"
author: "Mark Fernandes"
date: "2025-03-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r load-data}
#load tidyverse library
library(tidyverse) # used for data manipulation
library(rmarkdown) # used for paged_table function
library(kableExtra) # used for table
library(ggpubr) #used for ggarrange function 

#read file into R
pop_data <- read_csv("data/gapminder_data.csv")

#create a table with data from European countries in 2007 showing the countries 
#with the largest life expectancy at the top 
euro_data_tbl <- pop_data %>% 
                    filter(continent == "Europe" & year == 2007) %>% 
                    select(-continent, -year) %>% 
                    arrange(desc(lifeExp)) %>% 
                    rename(Country = country, "Population Size" = pop, 
                      "Life Expectancy" = lifeExp, "GDP" = gdpPercap)
    
```

Using Kable to knit a table.  
```{r kbl}
euro_data_tbl %>% 
          kbl()
```

Kable with more options. 
```{r kbl2}
euro_data_tbl %>% 
          kbl() %>%
          kable_styling(bootstrap_options = c("striped", "hover")) 
# NB error in notes - remove superfluous %>%
```

Using paged_table
```{r paged-table}
paged_table(euro_data_tbl)
```
